name: CMake on a single platform

on:
  push:
#    branches: [ "branch-name" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Configure CMake
      run: cmake -DCMAKE_PREFIX_PATH=/home/ubuntu/Qt/6.5.2/gcc_64 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --parallel 10 --config ${{env.BUILD_TYPE}}

